CREATE TABLE `users` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`mail`	TEXT NOT NULL UNIQUE,
	`pass`	TEXT NOT NULL
);

CREATE TABLE `rights` (
	`user_id`	INTEGER NOT NULL UNIQUE,
	`level`	INTEGER,
	PRIMARY KEY(`user_id`)
);